kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/cert-manager?ref=${K8S_GIT_BRANCH}

patchesStrategicMerge:

### Lets encrypt ACME certificate issuer for the cluster ###
- |-
  apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    name: letsencrypt-prod
  spec:
    acme:
      server: ${LETS_ENCRYPT_SERVER}
      email: ${CLUSTER_NAME_LC}@${DNS_ZONE}
      solvers:
      - dns01:
          route53:
            region: ${REGION}
            role: ${GLOBAL_DNS_IAM_ROLE}
        selector:
          dnsZones:
          - ${GLOBAL_TENANT_DOMAIN}
      - dns01:
          route53:
            region: ${REGION}
        selector:
          dnsZones:
          - ${DNS_ZONE}

### Lets encrypt ACME certificate for all endpoints ###
- |-
  apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: acme-tls-cert
    namespace: cert-manager
  spec:
    dnsNames:
    - '*.${ENV}.${GLOBAL_TENANT_DOMAIN}'
    - '*.${DNS_ZONE}'
    keystores:
      pkcs12:
        create: true
        # Password used to encrypt the keystore into which the ACME certs will be added
        passwordSecretRef:
          name: pingcommon-passwords
          key: ACME_CERT_KEYSTORE_PASSWORD
    # added to enable the auto-renewal functionality from cert-manager
    renewBefore: ${CERT_RENEW_BEFORE}
    
- |-
  # Add IRSA role annotation to cert-manager service account
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: cert-manager
    namespace: cert-manager
    annotations:
      purpose: service-account-for-cert-manager
      ${IRSA_CERT_MANAGER_ANNOTATION_KEY_VALUE}

- |-
  # Add IRSA role annotation to cert-manager-cainjector service account
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: cert-manager-cainjector
    namespace: cert-manager
    annotations:
      purpose: service-account-for-cert-manager-cainjector
      ${IRSA_CERT_MANAGER_ANNOTATION_KEY_VALUE}

- |-
  # Add IRSA role annotation to cert-manager-webhook service account
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: cert-manager-webhook
    namespace: cert-manager
    annotations:
      purpose: service-account-for-cert-manager-webhook
      ${IRSA_CERT_MANAGER_ANNOTATION_KEY_VALUE}

patchesJson6902:

# Change the namespace of the ACME certificate to the ping-cloud namespace
- target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    name: acme-tls-cert
    namespace: cert-manager
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: ${PING_CLOUD_NAMESPACE}
