apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds.yaml


# Patch the CRDs such that argocd will sync them properly
patchesJson6902:
  - target:
      version: v1
      kind: CustomResourceDefinition
      name: alertmanagerconfigs.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: alertmanagers.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"  

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: podmonitors.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"  

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: probes.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: prometheusagents.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: prometheuses.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"  

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: prometheusrules.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"  

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: scrapeconfigs.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: servicemonitors.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"  

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: thanosrulers.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: "ServerSideApply=true"