apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-notifications-cm.yaml
- argocd-notifications-controller-deployment.yaml
- argocd-notifications-controller-metrics-service.yaml 
- argocd-notifications-controller-role.yaml
- argocd-notifications-controller-rolebinding.yaml
- argocd-notifications-controller-sa.yaml
