kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
# PingCloud common resources
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingcommon?ref=${K8S_GIT_BRANCH}


configMapGenerator:

# PingCommon environment variables
- name: pingcommon-environment-variables
  behavior: merge
  envs:
  - ../../env_vars