kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- namespace.yaml
- ../base
- rbac.yaml
- hpa.yaml
- ingress-class.yaml

namespace: ingress-nginx-public

commonLabels:
  app.kubernetes.io/component: controller
  app.kubernetes.io/name: ingress-nginx
  app.kubernetes.io/part-of: ingress-nginx
  app.kubernetes.io/role: ingress-nginx-public
  app.kubernetes.io/version: 1.8.0

configMapGenerator:
- name: ingress-bootstrap-environment-variables
  literals:
    - SSM_PATH_DHPARAM=/pcpt/beluga/ingress-keys/ingress-nginx-public"
    - REGION=${REGION}

patchesJson6902:
- path: add-deployment-args.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-ingress-controller
- path: add-owasp-annotations.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-ingress-controller
- path: add-sigsci-sidecar.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-ingress-controller
- path: add-sigsci-configmap.yaml
  target:
    group: ""
    version: v1
    kind: ConfigMap
    name: nginx-configuration
- path: add-tcp-services-configmap.yaml
  target:
    group: ""
    version: v1
    kind: ConfigMap
    name: tcp-services
- path: add-tcp-protocol-service.yaml
  target:
    group: ""
    version: v1
    kind: Service
    name: ingress-nginx

patchesStrategicMerge:
- add-init-container.yaml
