apiVersion: v1
kind: ConfigMap
metadata:
  name: maintenance-mode
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
data:
  maintenance-mode: "disabled"