kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud

resources:
- ../../../../base/pingaccess/admin/aws

patchesStrategicMerge:
- admin-init-env.yaml
- admin-limits.yaml
