# NOTE: this file will be overwritten by dev-env.sh/utils.sh if provisioning is disabled
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../../../k8s-configs/ping-cloud/base/pingfederate/provisioning/aws

patchesStrategicMerge:
- |-
  apiVersion: postgres-operator.crunchydata.com/v1beta1
  kind: PostgresCluster
  metadata:
    name: pf-provisioning
  spec:
    backups:
      pgbackrest:
        global:
          # Use EC2 role-based authentication in dev clusters
          repo1-s3-key-type: auto
        repos:
          - name: repo1
            s3:
              bucket: "${BACKUP_BUCKET_NAME}"
              endpoint: "s3.${REGION}.amazonaws.com"
              region: "${REGION}"
            schedules:
              full: "0 0 * * *"
              differential: "30 */6 * * *"

### Uncomment the below patch to execute a PGO database restore for pf-provisioning
### ***NOTE: This action will bring down the database until the restoration is complete!***
### If this has been executed before, the id number will need to be incremented to kick off a new restore job
### This can also be done via command line with the below command
### kubectl annotate -n postgres-operator postgrescluster pf-provisioning --overwrite postgres-operator.crunchydata.com/pgbackrest-restore=id1
#- |-
#  apiVersion: postgres-operator.crunchydata.com/v1beta1
#  kind: PostgresCluster
#  metadata:
#    name: pf-provisioning
#    annotations:
#      postgres-operator.crunchydata.com/pgbackrest-restore: id1