# This defines the ingress for the pingaccess runtime service

# NOTE: it will only work if an ingress controller (e.g. nginx) is running on
# your cluster.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingaccess-ingress
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: nginx-public
spec:
  tls:
  - hosts:
    - pingaccess-dev.ping-demo.com
    secretName: tls-secret-pingaccess-ingress
  rules:
  - host: pingaccess-dev.ping-demo.com
    http:
      paths:
      # This rule gives external access to the pingaccess runtime service
      - path: /
        backend:
          serviceName: pingaccess
          servicePort: 443

---

# This defines the ingress for the pingaccess admin service

# NOTE: it will only work if an ingress controller (e.g. nginx) is running on
# your cluster.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingaccess-admin-ingress
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: nginx-private
spec:
  tls:
  - hosts:
    - pingaccess-admin-dev.ping-demo.com
    secretName: tls-secret-pingaccess-admin-ingress
  rules:
  - host: pingaccess-admin-dev.ping-demo.com
    http:
      paths:
      # This rule gives internal access to the pingaccess admin services.
      - path: /
        backend:
          serviceName: pingaccess
          servicePort: 9000

---

# This defines the ingress for the pingaccess agent services.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingaccess-agent-ingress
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: nginx-public
spec:
  tls:
  - hosts:
    - pingaccess-agent-dev.ping-demo.com
    secretName: tls-secret-pingaccess-agent-ingress
  rules:
  - host: pingaccess-agent-dev.ping-demo.com
    http:
      paths:
      # This rule gives external access to the pingaccess agent port
      - path: /
        backend:
          serviceName: pingaccess
          servicePort: 3030