########################################################################################################################
# Customer region-specific parameters that are shared by multiple apps
########################################################################################################################

global:
  # region is the AWS region name
  region: "${REGION}"
  regionNickname: "${REGION_NICK_NAME}"

  # The name of the tenant
  tenantName: "${TENANT_NAME}"

  # tenantDomain is the domain suffix for customer for region
  tenantDomain: "${TENANT_DOMAIN}"

  # dnsZone is the Customer-specific region DNS zone
  dnsZone: "${VALUES_FILES_DNS_ZONE}"

  # irsaPingAnnotationKeyValue is the IAM roles for service accounts
  irsaPingAnnotationKeyValue: "${IRSA_PING_ANNOTATION_KEY_VALUE}"