apiVersion: apps/v1
kind: Deployment
metadata:
  name: p14c-oauth-service
spec:
  selector:
    matchLabels:
      role: p14c-oauth-service
  replicas: 1
  template:
    metadata:
      name: p14c-oauth-service
      labels:
        role: p14c-oauth-service
    spec:
      serviceAccount: p14c-oauth-serviceaccount
      containers:
      - name: pingcloud-oauth
        image: public.ecr.aws/r2h3l6e4/pingcloud-services/p14c-integration:v1.0.17
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: p14c-oauth-service-environment-variables
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # The -u flag is necessary for python to emit logging to standard out
        command: [ 'python3', '-u', '/app/oauth_client_services_controller.py' ]
        livenessProbe:
          exec:
            command: [ 'python3', '-u', '/app/liveness.py' ]
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3
          timeoutSeconds: 3
