apiVersion: apps/v1
kind: Deployment
metadata:
  name: p14c-oauth-service
spec:
  selector:
    matchLabels:
      role: p14c-oauth-service
  replicas: 1
  template:
    metadata:
      name: p14c-oauth-service
      labels:
        role: p14c-oauth-service
    spec:
      serviceAccount: p14c-oauth-serviceaccount
      containers:
      - name: pingcloud-oauth
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 9999
          runAsNonRoot: true
          runAsUser: 9031
        image: public.ecr.aws/r2h3l6e4/pingcloud-services/p14c-integration/dev:v1.19-release-branch-latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: p14c-oauth-service-environment-variables
        env:
          - name: PA_ADMIN_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pingaccess-passwords
                key: PA_ADMIN_USER_PASSWORD
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        # The -u flag is necessary for python to emit logging to standard out
        command: [ 'python3', '-u', '/app/oauth_client_services_controller.py' ]
        livenessProbe:
          exec:
            command: [ 'python3', '-u', '/app/liveness.py' ]
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3
          timeoutSeconds: 3
