kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  role: pingaccess

configMapGenerator:
- name: pingaccess-environment-variables
  env: env_vars

secretGenerator:
- name: pingaccess-secret-variables
  env: secret_vars