apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingcentral-passwords
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    argocd.argoproj.io/sync-options: Prune=false
data:
  OLD_PC_ADMIN_USER_PASSWORD: MkZlZGVyYXRl
  PC_ADMIN_USER_PASSWORD: MkZlZGVyYXRlTTByZQ==
