apiVersion: apps/v1
kind: Deployment
metadata:
  name: p14c-bom-service
spec:
  selector:
    matchLabels:
      role: p14c-bom-service
  replicas: 1
  template:
    metadata:
      name: p14c-bom-service
      labels:
        role: p14c-bom-service
    spec:
      serviceAccount: p14c-bom-serviceaccount
      containers:
      - name: pingcloud-bom
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 9999
          runAsNonRoot: true
          runAsUser: 9031
        image: public.ecr.aws/r2h3l6e4/pingcloud-services/p14c-integration/dev:v1.19-release-branch-latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: p14c-bom-service-environment-variables
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # The -u flag is necessary for python to emit logging to standard out
        command: [ 'python3', '-u', '/app/bom_service_controller.py' ]
        livenessProbe:
          exec:
            command: [ 'python3', '-u', '/app/liveness.py'  ]
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3
          timeoutSeconds: 3
