kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- minimal-secret.yaml
#- baseline-secret.yaml
- configmap.yaml
# FIXME: Will move periodic-backup.yaml to code-gen before kube mode 1
# - periodic-backup.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingfederate-environment-variables
  envs:
  - env_vars