kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- secret.yaml
- configmap.yaml
- storage.yaml  
- statefulset-admin.yaml
- deployment-engine.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingfederate-environment-variables
  envs:
  - env_vars
