# This defines the Ping DataSync deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingdatasync
  labels:
    class: pingdatasync-server
spec:
  replicas: 1
  selector:
    matchLabels:
      class: pingdatasync-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        lastUpdateReason: "NA"
      labels:
        class: pingdatasync-server
    spec:
      serviceAccountName: ping-serviceaccount
      terminationGracePeriodSeconds: 300
      initContainers:
      - name: wait-for-pds
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        image: public.ecr.aws/r2h3l6e4/busybox:1.32
        imagePullPolicy: IfNotPresent
        command:
          - /wait-for-pds.sh
        volumeMounts:
          - name: pingdatasync-init
            mountPath: /utils.lib.sh
            subPath: utils.lib.sh
          - name: pingdatasync-init
            mountPath: /logger.lib.sh
            subPath: logger.lib.sh
          - name: pingdatasync-init
            mountPath: /wait-for-pds.sh
            subPath: wait-for-pds.sh
        envFrom:
          - configMapRef:
              name: pingdatasync-environment-variables
      - name: pingdatasync-init
        securityContext:
          runAsGroup: 9999
          runAsNonRoot: true
          runAsUser: 9031
        image: public.ecr.aws/r2h3l6e4/bitnami/kubectl:1.15.3
        imagePullPolicy: IfNotPresent
        command:
          - /copy-dependencies.sh
        volumeMounts:
          - name: ssh-dir
            mountPath: /.ssh
          - name: data-dir
            mountPath: /data
          - name: ssh-id-key-secret
            mountPath: /id_rsa
            subPath: id_rsa
          - name: known-hosts-config
            mountPath: /known_hosts
            subPath: known_hosts
          - name: pingdatasync-init
            mountPath: /copy-dependencies.sh
            subPath: copy-dependencies.sh
          - name: pingdatasync-init
            mountPath: /utils.lib.sh
            subPath: utils.lib.sh
          - name: pingdatasync-init
            mountPath: /logger.lib.sh
            subPath: logger.lib.sh
        env:
          - name: P1AS_PD_LDAPS_PORT
            valueFrom:
              configMapKeyRef:
                name: pingdirectory-environment-variables
                key: LDAPS_PORT
        envFrom:
          - configMapRef:
              name: pingdatasync-environment-variables
      containers:
      - name: pingdatasync
        securityContext:
          runAsGroup: 9999
          runAsNonRoot: true
          runAsUser: 9031
        image: public.ecr.aws/r2h3l6e4/pingcloud-apps/pingdatasync:8.2.0.6-v1.0.11
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"
          requests:
            memory: "4Gi"
            cpu: "2"
        readinessProbe:
          exec:
            command: [/opt/readiness.sh]
          initialDelaySeconds: 90
          periodSeconds: 5
          failureThreshold: 5
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command: [/opt/liveness.sh]
          initialDelaySeconds: 90
          periodSeconds: 30
          failureThreshold: 5
          timeoutSeconds: 5
        ports:
          - name: ldap
            containerPort: 1389
          - name: ldaps
            containerPort: 1636
          - name: https
            containerPort: 1443
        env:
          - name: ROOT_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pingdatasync-passwords
                key: root-user-password
          - name: EXT_PD_SYNC_BIND_DN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pingdatasync-passwords
                key: EXT_PD_SYNC_BIND_DN_PASSWORD
          - name: EXT_PD_ADMIN_BIND_DN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pingdatasync-passwords
                key: EXT_PD_ADMIN_BIND_DN_PASSWORD
          - name: P1AS_PD_SYNC_BIND_DN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pingdirectory-passwords
                key: root-user-password
          - name: P1AS_PD_LDAPS_PORT
            valueFrom:
              configMapKeyRef:
                name: pingdirectory-environment-variables
                key: LDAPS_PORT
          - name: P1AS_PD_ADMIN_BIND_DN
            valueFrom:
              configMapKeyRef:
                name: pingdirectory-environment-variables
                key: ADMIN_BIND_DN
          - name: P1AS_PD_SYNC_BIND_DN
            valueFrom:
              configMapKeyRef:
                name: pingdirectory-environment-variables
                key: SYNC_BIND_DN
          - name: PINGDATASYNC_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PINGDATASYNC_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: PINGDATASYNC_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        envFrom:
          - configMapRef:
              name: pingdatasync-environment-variables
          - configMapRef:
              name: pingcommon-environment-variables
        volumeMounts:
          - name: ssh-dir
            mountPath: /home/ping/.ssh
          - name: data-dir
            mountPath: /usr/local/bin/kubectl
            subPath: kubectl
          - name: data-dir
            mountPath: /opt/staging/ds_env_vars
            subPath: ds_env_vars
          - name: data-dir
            mountPath: /usr/local/bin/skbn
            subPath: skbn
          - name: data-dir
            mountPath: /opt/staging/hooks/logger.lib.sh
            subPath: logger.lib.sh
          - name: topology-descriptor
            mountPath: /opt/staging/topology/descriptor.json
            subPath: descriptor.json
          - name: pingdatasync-passwords
            mountPath: /usr/local/secrets
            readOnly: true
          - name: pingdirectory-license
            mountPath: /opt/in/instance/conf/PingDirectory.lic
            subPath: PingDirectory.lic
      securityContext:
        fsGroup: 9999
      volumes:
        - name: ssh-dir
          emptyDir: {}
        - name: data-dir
          emptyDir: {}
        - name: pingdatasync-init
          configMap:
            name: pingcommon-init
            defaultMode: 0555
        - name: topology-descriptor
          configMap:
            name: topology-descriptor
            optional: true
            defaultMode: 0644
        - name: ssh-id-key-secret
          secret:
            secretName: ssh-id-key-secret
            optional: true
            defaultMode: 0400
        - name: known-hosts-config
          configMap:
            name: known-hosts-config
            optional: true
            defaultMode: 0644
        - name: pingdatasync-passwords
          secret:
            secretName: pingdatasync-passwords
            optional: true
            defaultMode: 0400
        - name: pingdirectory-license
          secret:
            secretName: pingdirectory-license
            optional: true
            defaultMode: 0400
