kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ${PING_CLOUD_NAMESPACE}

resources:
  - ../base
  - custom-resources

helmCharts:
  - name: p1as-beluga-tools
    additionalValuesFiles:
      - ../../values-files/base/values.yaml   # base values.yaml
      - ../../values-files/${REGION_NICK_NAME}/values.yaml   # regional values.yaml
      - values.yaml   # app specific values.yaml
    includeCRDs: true
    # TODO: Test this being set for feature testing, release branch testing, & releases/release candidates
    version: v1.18-kfox-test
    repo: oci://${ECR_REGISTRY_NAME}/p1as-beluga-tools

patchesStrategicMerge:
  ### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###
  - custom-patches.yaml

# TODO: figure this out
#configMapGenerator:
#  - name: last-update-reason
#    literals:
#      - UPDATE_REASON="seal non-base64 secrets"