kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
- ../../../base/logging/

patchesStrategicMerge:
- elastic-stack/logstash/logstash-limits.yaml
- elastic-stack/logstash/hpa-limits.yaml
- elastic-stack/opensearch/os-limits.yaml
