kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/cluster-tools?ref=${K8S_GIT_BRANCH}

# Include flux CD here so flux can update itself in the future
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/git-ops?ref=${K8S_GIT_BRANCH}
- known-hosts-config.yaml

patchesStrategicMerge:

### Lets encrypt ACME certificate issuer for the cluster ###
- |-
  apiVersion: certmanager.k8s.io/v1alpha1
  kind: ClusterIssuer
  metadata:
    name: letsencrypt-prod
  spec:
    acme:
      server: ${LETS_ENCRYPT_SERVER}
      email: ${CLUSTER_NAME_LC}@${DNS_ZONE}
      solvers:
      - dns01:
          route53:
            region: ${REGION}
        selector:
          dnsZones:
          - ${DNS_ZONE}

### Lets encrypt ACME certificate for all endpoints ###
- |-
  apiVersion: certmanager.k8s.io/v1alpha1
  kind: Certificate
  metadata:
    name: acme-tls-cert
    namespace: cert-manager
  spec:
    dnsNames:
    - '*.${DNS_ZONE}'
    commonName: ${DNS_ZONE}

### External DNS service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: external-dns
    namespace: external-dns
    annotations:
      purpose: service-account-for-external-dns

### Additional args to the flux deployment object ###
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: flux
    namespace: flux
  spec:
    template:
      spec:
        containers:
        - name: flux
          args:
          - --manifest-generation=true
          - --listen-metrics=:3031
          - --git-poll-interval=60s
          - --git-url=${CLUSTER_STATE_REPO_URL}
          - --git-branch=${CLUSTER_STATE_REPO_BRANCH}
          - --git-path=k8s-configs/${CLUSTER_STATE_REPO_PATH}
          - --git-readonly
          - --registry-disable-scanning
          volumeMounts:
          - name: ssh-config
            mountPath: /root/.ssh
        volumes:
        - name: ssh-config
          configMap:
            name: flux-ssh-config
            defaultMode: 0644

### Cloud-watch logging and monitoring ###
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: cluster-info
    namespace: amazon-cloudwatch
  data:
    cluster.name: ${CLUSTER_NAME}
    logs.region: ${REGION}

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: cwagentconfig
    namespace: amazon-cloudwatch
  data:
    # Configuration is in Json format. No matter what configure change you make,
    # please keep the Json blob valid.
    cwagentconfig.json: |
      {
        "agent": {
          "region": "${REGION}"
        },
        "logs": {
          "metrics_collected": {
            "kubernetes": {
              "cluster_name": "${CLUSTER_NAME}",
              "metrics_collection_interval": 60
            }
          },
          "force_flush_interval": 5
        }
      }

patchesJson6902:

### Change the default TLS secret for the ingress controllers ###
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-ingress-controller
    namespace: ingress-nginx-private
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value:
        --default-ssl-certificate=${PING_CLOUD_NAMESPACE}/acme-tls-cert

- target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-ingress-controller
    namespace: ingress-nginx-public
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value:
        --default-ssl-certificate=${PING_CLOUD_NAMESPACE}/acme-tls-cert

### Cluster auto-scaler ###
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cluster-autoscaler
    namespace: kube-system
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value:
        --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/${CLUSTER_NAME}
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: AWS_REGION
          value: ${REGION}

# Change the namespace of the ACME certificate to the ping-cloud namespace
- target:
    group: certmanager.k8s.io
    version: v1alpha1
    kind: Certificate
    name: acme-tls-cert
    namespace: cert-manager
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: ${PING_CLOUD_NAMESPACE}

# Configure external-dns to only own the hosted zone for the tenant domain
- target:
    group: apps
    version: v1
    kind: Deployment
    name: external-dns
    namespace: external-dns
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value:
        --domain-filter=${DNS_ZONE}.