# p1as-cluster-tools prod settings

# ingress-nginx-public values
ingress-nginx-public:
  ingress-nginx:
    controller:
      autoscaling:
        minReplicas: 4
        maxReplicas: 6
        targetCPUUtilizationPercentage: 40
      config:
        # prod config settings
        # migrated from PCB/k8s-configs/cluster-tools/prod/small/ingress/nginx
        #
        # We will be removing these configmap settings for non-small customer environments automatically in PDO-9756
        # and re-evaluating them for all environments in PDO-9757
        keep-alive-requests: "100000"
        upstream-keepalive-timeout: "30"
