kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: ${PING_CLOUD_NAMESPACE}
commonLabels:
  app: ping-cloud
  role: pingdirectory
resources:
  - ../base/custom-resources
  - custom-resources
helmCharts:
  - name: p1as-pingdirectory
    additionalValuesFiles:
      - ../../values-files/base/values.yaml # base values.yaml
      - ../../values-files/${REGION_NICK_NAME}/values.yaml # regional values.yaml
      - values.yaml # app specific values.yaml
    version: v2.2.0-RC4
    repo: oci://${ECR_REGISTRY_NAME}
### This field is used to trigger a resync of the p1as-pingdirectory helm chart ###
configMapGenerator:
  - name: pingdirectory-last-update-reason
    literals:
      - UPDATE_REASON=""
  ### This is needed for the empty custom-patches.yaml file to work ###
  - name: pingdirectory-custom-placeholder
  ### This is needed for the empty custom-patches.yaml file to work in base folder ###
  - name: pingdirectory-custom-placeholder-base
patchesStrategicMerge:
  ### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###
  - custom-patches.yaml
  - ../base/custom-patches.yaml
