pingdirectory:  
  backupFileName: ""
  # This is the environment variable to select the backend(s) to restore in PD
  # Allowed values:appintegrations platformconfig userRoot userRoot_2 userRoot_3 userRoot_4 userRoot_5
  # Seperated with a semi-colon(;) Example: userRoot;userRoot_2
  # No values set would just restore all backends in PD
  backendsToRestore: ""
  monitorBucketUrl: "${PD_MONITOR_BUCKET_URL}"
  # Changes PURGE_BATCH_SIZE for -Dcom.unboundid.directory.server.plugins.PurgeExpiredDataPlugin.BATCH_SIZE= - default is 10000
  purgeBatchSize: "10000"
  maxHeapSize: "15g"
  # Add auth cert(s) - space delimited if multiple - here to enable X.509-based authentication via SASL
  # More info here: https://confluence.pingidentity.com/display/proserv/Enabling+X.509+Authentication+with+PingDirectory
  # Example: PD_X509_AUTH_CERTS=cert_one cert_two
  pdX509AuthCerts: ""
  # Set to false to avoid skipping liveness probe. Skipping the liveness (SKIP_LIVENESS=true) is the default for PingDirectory.
  skipLiveness: true
  # Customization for pingdirectory ingress resource
  ingress:
    enableExternalIngress: false
  statefulSet:
    lastUpdateReason: "NA"
    replicas: "3"
    # Set container limits for the pingdirectory deployment
    pingdirectory:
      resources:
        limits:
          memory: "26Gi"
          cpu: "3"
        requests:
          memory: "22Gi"
          cpu: "2"
    statsdExporter:
      resources:
        limits:
          cpu: "100m"
          memory: "300Mi"
        requests:
          cpu: "100m"
          memory: "300Mi"
  # Persistent volume size configuration.
  persistentVolume:
    size: 100Gi
  # PingDirectory Shared Cache Settings 
  # Set this to 'true' to use shared cache for the local backends
  pdUseSharedCache: "false"
  # Set this to define overall cache size .This would to be shared across all local backends
  sharedCachePercent: "55"