kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
# Apply PingFederate admin deployment resources
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingfederate/admin?ref=${K8S_GIT_BRANCH}

images:

- name: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingfederate${ECR_ENV}
  newName: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingfederate${ECR_ENV}
  newTag: ${PINGFEDERATE_IMAGE_TAG}

- name: ${ECR_REGISTRY_NAME}/pingcloud-services/p14c-integration${ECR_ENV}
  newName: ${ECR_REGISTRY_NAME}/pingcloud-services/p14c-integration${ECR_ENV}
  newTag: ${P14C_INTEGRATION_IMAGE_TAG}

patchesJson6902:

### PingFederate Admin Last Update Config Map ###
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: pingfederate-admin
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: pingfederate-admin-last-update-config

### Ingress patches ###

# pingfederate admin api
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingfederate-admin-ingress
  patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingfederate-admin-api.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: pingfederate-admin-api.${DNS_ZONE}

# Set a hostname for all the headless services so their endpoint IPs are published to Route53
- target:
    version: v1
    kind: Service
    name: pingfederate-cluster
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingfederate-cluster.${DNS_ZONE}
