kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
# Apply PingAccess-WAS runtime engine deployment resources
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingaccess-was/engine?ref=${K8S_GIT_BRANCH}

images:
- name: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingaccess-was${ECR_ENV}
  newName: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingaccess-was${ECR_ENV}
  newTag: ${PINGACCESS_WAS_IMAGE_TAG}

patchesJson6902:

### PingAccess WAS Engine Last Update Config Map ###
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: pingaccess-was
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: pingaccess-was-last-update-config

### Ingress patches ###

# PingAccess admin and PingFederate admin through PingAccess-WAS
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingaccess-was-ingress
  patch: |
    # PingAccess admin through PingAccess-WAS
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess-admin.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess-admin.${DNS_ZONE}

    # PingFederate admin through PingAccess-WAS
    - op: replace
      path: /spec/tls/0/hosts/1
      value: pingfederate-admin.${DNS_ZONE}
    - op: replace
      path: /spec/rules/1/host
      value: pingfederate-admin.${DNS_ZONE}

    # Grafana to pingaccess was runtime
    - op: replace
      path: /spec/tls/0/hosts/2
      value: monitoring.${DNS_ZONE}
    - op: replace
      path: /spec/rules/2/host
      value: monitoring.${DNS_ZONE}

    # Prometheus to pingaccess was runtime
    - op: replace
      path: /spec/tls/0/hosts/3
      value: prometheus.${DNS_ZONE}
    - op: replace
      path: /spec/rules/3/host
      value: prometheus.${DNS_ZONE}

    # OpenSearch Dashboards pingaccess was runtime
    - op: replace
      path: /spec/tls/0/hosts/4
      value: logs.${DNS_ZONE}
    - op: replace
      path: /spec/rules/4/host
      value: logs.${DNS_ZONE}

    # Remove PingCentral from PA-WAS in CDE
    - op: remove
      path: /spec/tls/0/hosts/5
    - op: remove
      path: /spec/rules/5

    # Healthcheck httpbin service through PA-WAS engines
    - op: replace
      path: /spec/tls/0/hosts/5
      value: healthcheck-httpbin-pa-was.${DNS_ZONE}
    - op: replace
      path: /spec/rules/5/host
      value: healthcheck-httpbin-pa-was.${DNS_ZONE}

    # Remove Argo CD from PA-WAS in CDE 
    - op: remove
      path: /spec/tls/0/hosts/6
    - op: remove
      path: /spec/rules/6
