# This defines the Ping Central deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingcentral
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingcentral
  strategy:
    type: Recreate
  template:
    metadata:
      name: pingcentral
      annotations:
        lastUpdateReason: "NA"
      labels:
        role: pingcentral
        entitled-app: "true"
    spec:
      serviceAccount: ping-serviceaccount
      affinity:
        podAntiAffinity:
          # Add a soft requirement for each DA pod to be deployed to a different AZ
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - pingcentral
                topologyKey: "topology.kubernetes.io/zone"
      initContainers:
      - name: pingcentral-init
        securityContext:
          runAsGroup: 9999
          runAsNonRoot: true
          runAsUser: 9031
          allowPrivilegeEscalation: false
        image: public.ecr.aws/r2h3l6e4/pingcloud-services/toolkit:v1.15.0
        imagePullPolicy: IfNotPresent
        command:
          - /copy-dependencies.sh
        volumeMounts:
          - name: ssh-dir
            mountPath: /.ssh
          - name: data-dir
            mountPath: /data
          - name: ssh-id-key-secret
            mountPath: /id_rsa
            subPath: id_rsa
          - name: known-hosts-config
            mountPath: /known_hosts
            subPath: known_hosts
          - name: pingcentral-init
            mountPath: /copy-dependencies.sh
            subPath: copy-dependencies.sh
          - name: pingcentral-init
            mountPath: /utils.lib.sh
            subPath: utils.lib.sh
          - name: pingcentral-init
            mountPath: /logger.lib.sh
            subPath: logger.lib.sh
        envFrom:
          - configMapRef:
              name: pingcentral-environment-variables
      - name: newrelic-tags-exporter
        securityContext:
          runAsGroup: 9999
          runAsNonRoot: true
          runAsUser: 9031
          allowPrivilegeEscalation: false
        image: public.ecr.aws/r2h3l6e4/pingcloud-monitoring/newrelic-tags-exporter/dev:v1.19-release-branch-latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: pingcentral-environment-variables
        - secretRef:
            name: newrelic-license-key
            optional: false
        env:
        - name: NEW_RELIC_APP_NAME
          value: "pingcentral"
        - name: METADATA_EP_URL
          value: "http://metadata:5000"
        - name: NEW_RELIC_CONFIG_FILEPATH
          value: "/opt/shared-dir/newrelic.yml"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
          value: "true"
        volumeMounts:
        - name: shared-dir
          mountPath: /opt/shared-dir
      containers:
      - name: pingcentral
        securityContext:
          runAsGroup: 9999
          runAsNonRoot: true
          runAsUser: 9031
          allowPrivilegeEscalation: false
        image: public.ecr.aws/r2h3l6e4/pingcloud-apps/pingcentral/dev:v1.19-release-branch-latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "5Gi"
            cpu: "2"
        readinessProbe:
          exec:
            command: [/opt/readiness.sh]
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command: [/opt/liveness.sh]
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 4
          timeoutSeconds: 5
        ports:
          - name: https
            containerPort: 9022
        env:
          - name: OLD_PC_ADMIN_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pingcentral-passwords
                key: OLD_PC_ADMIN_USER_PASSWORD
          - name: PC_ADMIN_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pingcentral-passwords
                key: PC_ADMIN_USER_PASSWORD
          - name: NEW_RELIC_CONFIG_FILE
            value: "/opt/shared-dir/newrelic.yml"
          - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
            value: "true"
        envFrom:
          - configMapRef:
              name: pingcentral-environment-variables
          - secretRef:
              name: newrelic-license-key
              optional: false
        volumeMounts:
          - name: ssh-dir
            mountPath: /home/ping/.ssh
          - name: shared-dir
            mountPath: /opt/shared-dir
          - name: topology-descriptor
            mountPath: /opt/staging/topology/descriptor.json
            subPath: descriptor.json
          - name: data-dir
            mountPath: /usr/local/bin/kubectl
            subPath: kubectl
          - name: data-dir
            mountPath: /opt/staging/ds_env_vars
            subPath: ds_env_vars
          - name: data-dir
            mountPath: /opt/staging/hooks/logger.lib.sh
            subPath: logger.lib.sh
          - name: pingcentral-passwords
            mountPath: /usr/local/secrets
            readOnly: true
          - name: pingcentral-license
            mountPath: /opt/in/instance/conf/pingcentral.lic
            subPath: pingcentral.lic
          - name: data-dir
            mountPath: /opt/staging/newrelic.jar
            subPath: newrelic.jar
      securityContext:
        fsGroup: 9999
      volumes:
        - name: ssh-dir
          emptyDir: {}
        - name: shared-dir
          emptyDir: {}
        - name: data-dir
          emptyDir: {}
        - name: pingcentral-init
          configMap:
            name: pingcommon-init
            defaultMode: 0555
        - name: topology-descriptor
          configMap:
            name: topology-descriptor
            optional: true
            defaultMode: 0644
        - name: ssh-id-key-secret
          secret:
            secretName: ssh-id-key-secret
            optional: true
            defaultMode: 0400
        - name: known-hosts-config
          configMap:
            name: known-hosts-config
            optional: true
            defaultMode: 0644
        - name: pingcentral-license
          secret:
            secretName: pingcentral-license
            optional: true
            defaultMode: 0400
        - name: pingcentral-passwords
          secret:
            secretName: pingcentral-passwords
            optional: true
            defaultMode: 0400
