kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud
  role: pingcentral

resources:
- statefulset.yaml
- service.yaml
- ingress.yaml
- storage.yaml
- snapshot-class.yaml
- volume-snapshot.yaml