---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "true"
      disable_signout_menu: "true"
    auth.anonymous:
      enabled: "false"
    auth.proxy:
      enabled: "true"
      header_name: "X-Webauth-Email"
      header_property: "username"
      auto_sign_up: "true"
      sync_ttl: "60"
      headers: "Email:X-Webauth-Email, Role:X-Webauth-Role"
    security:
      admin_user: admin
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/grafana/grafana:10.1.0
              env:
                - name: GF_INSTALL_PLUGINS
                  value: "grafana-opensearch-datasource 2.5.1"
              securityContext:
                runAsUser: 472
                runAsNonRoot: true
                runAsGroup: 472
              resources:
                limits:
                  cpu: 500m
                  memory: 2500Mi
                requests:
                  cpu: 100m
                  memory: 100Mi