# This defines the ingress for the pingaccess runtime service

# NOTE: it will only work if an ingress controller (e.g. nginx) is running on
# your cluster.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingaccess-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    self-service.metadata.pingidentity.com/name: "PingAccess Runtime"
    self-service.metadata.pingidentity.com/description: "Default endpoint for servicing identity and access management requests when using gateway deployment model"
    self-service.metadata.pingidentity.com/category: "Informational"
    self-service.metadata.pingidentity.com/displayURL: "https://pingaccess-dev.ping-demo.com/"
  labels:
    self-service.urls/managed: "true"
spec:
  ingressClassName: nginx-public
  tls:
  - hosts:
    - pingaccess-dev.ping-demo.com
    - healthcheck-httpbin-pa-dev.ping-demo.com
  rules:
  - host: pingaccess-dev.ping-demo.com
    http:
      paths:
      # This rule gives external access to the pingaccess runtime service
      - pathType: Prefix
        path: /
        backend:
          service:
            name: pingaccess
            port:
              number: 443
  - host: healthcheck-httpbin-pa-dev.ping-demo.com
    http:
      paths:
      # This rule allows external access to the healthcheck-httpbin-pa service via the pingaccess runtime service
      - pathType: Prefix
        path: /
        backend:
          service:
            name: pingaccess
            port:
              number: 443

---

# This defines the ingress to allow Route53 health checks to pingacess

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingaccess-route53-health-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_cache heartbeat_cache;
      proxy_cache_valid 200 1s;
      proxy_ignore_headers Cache-Control Expires Set-Cookie;
spec:
  ingressClassName: nginx-public
  tls:
  - hosts:
    - pingaccess-dev.ping-demo.com
  rules:
  - host: pingaccess-dev.ping-demo.com
    http:
      paths:
      # This rule gives external access to the pingaccess runtime service
      - pathType: Exact
        path: /pa/heartbeat.ping
        backend:
          service:
            name: pingaccess
            port:
              number: 443

---

# This defines the ingress for the pingaccess agent services.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingaccess-agent-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    self-service.metadata.pingidentity.com/name: "PingAccess Agent"
    self-service.metadata.pingidentity.com/description: "Default endpoint for servicing identity and access management requests when using agent deployment model"
    self-service.metadata.pingidentity.com/category: "Informational"
    self-service.metadata.pingidentity.com/displayURL: "https://pingaccess-agent-dev.ping-demo.com/"
  labels:
    self-service.urls/managed: "true"
spec:
  ingressClassName: nginx-public
  tls:
  - hosts:
    - pingaccess-agent-dev.ping-demo.com
  rules:
  - host: pingaccess-agent-dev.ping-demo.com
    http:
      paths:
      # This rule gives external access to the pingaccess agent port
      - pathType: Prefix
        path: /
        backend:
          service:
            name: pingaccess
            port:
              number: 3030

