# This defines the ingress for the pingaccess runtime service

# NOTE: it will only work if an ingress controller (e.g. nginx) is running on
# your cluster.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingaccess-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx-public
spec:
  tls:
  - hosts:
    - pingaccess-dev.ping-demo.com
  rules:
  - host: pingaccess-dev.ping-demo.com
    http:
      paths:
      # This rule gives external access to the pingaccess runtime service
      - path: /
        backend:
          serviceName: pingaccess
          servicePort: 443

---

# This defines the ingress for the pingaccess agent services.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingaccess-agent-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx-public
spec:
  tls:
  - hosts:
    - pingaccess-agent-dev.ping-demo.com
  rules:
  - host: pingaccess-agent-dev.ping-demo.com
    http:
      paths:
      # This rule gives external access to the pingaccess agent port
      - path: /
        backend:
          serviceName: pingaccess
          servicePort: 3030
