# This defines the ingress for the pingaccess runtime service

# NOTE: it will only work if an ingress controller (e.g. nginx) is running on
# your cluster.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingaccess-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx-public
  tls:
  - hosts:
    - pingaccess-dev.ping-demo.com
    - healthcheck-httpbin-pa-dev.ping-demo.com
  rules:
  - host: pingaccess-dev.ping-demo.com
    http:
      paths:
      # This rule gives external access to the pingaccess runtime service
      - pathType: Prefix
        path: /
        backend:
          service:
            name: pingaccess
            port:
              number: 443
  - host: healthcheck-httpbin-pa-dev.ping-demo.com
    http:
      paths:
      # This rule allows external access to the healthcheck-httpbin-pa service via the pingaccess runtime service
      - pathType: Prefix
        path: /
        backend:
          service:
            name: pingaccess
            port:
              number: 443


---

# This defines the ingress for the pingaccess agent services.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingaccess-agent-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx-public
  tls:
  - hosts:
    - pingaccess-agent-dev.ping-demo.com
  rules:
  - host: pingaccess-agent-dev.ping-demo.com
    http:
      paths:
      # This rule gives external access to the pingaccess agent port
      - pathType: Prefix
        path: /
        backend:
          service:
            name: pingaccess
            port:
              number: 3030

