# This defines the ingress for the pingfederate authorization services.

# NOTE: it will only work if an ingress controller (e.g. nginx) is running on
# your cluster.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingfederate-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx-public
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
    Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
    SecRequestBodyAccess On
    SecAuditEngine RelevantOnly
    SecAuditLogParts ABIJDEFHZ
    SecAuditLog /dev/stdout
spec:
  tls:
  - hosts:
    - pingfederate-dev.ping-demo.com
  rules:
  - host: pingfederate-dev.ping-demo.com
    http:
      paths:
      # This rule gives external access to the pingfederate AS endpoints
      - path: /
        backend:
          serviceName: pingfederate
          servicePort: 9031

---

# This defines the ingress for the pingfederate admin services.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingfederate-admin-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx-private
spec:
  tls:
    - hosts:
        - pingfederate-admin-dev.ping-demo.com
  rules:
    - host: pingfederate-admin-dev.ping-demo.com
      http:
        paths:
          # This rule gives internal access to the pingfederate admin services.
          - path: /
            backend:
              serviceName: pingfederate-admin
              servicePort: 9999

