# ==================================================================================================================== #
#                                                    README                                                            #
# ==================================================================================================================== #

# This file separates the Ping applications into their individual components so that the apps may be rolled out in
# proper dependency order, especially when their versions are changing.

# For example, pingaccess-was-admin should be upgraded before pingaccess-was engines, so 2 separate rollouts are
# necessary. On the 1st rollout, comment out the "pingaccess-was/engine" line, and on the 2nd rollout, uncomment it.
# It's okay to leave the "pingaccess-was/admin" uncommented out on the 2nd rollout since its deployment should be
# idempotent.

# When changes are made to this file, corresponding changes may be required to custom-patches.yaml and to each
# secondary region's kustomization.yaml file where resources are removed from secondary, basically because you can't
# patch a resource that's not included.

# IMPORTANT: After all the applications are updated, reset this file and the two mentioned above back to its original
# contents.

# Since the CD tool is set to auto-prune by default, commenting out apps will remove them from the cluster. To prevent
# that from happening, auto-prune must be turned off in k8s-configs/base/cluster-tools/git-ops/argo-application.yaml.
# Do NOT proceed with granular updates of apps without doing that first.

# Additionally, before upgrading Beluga from one version to another, the default poll interval of the CD tool may
# temporarily need to be increased so that it doesn't interfere with changes that are still being made to the
# cluster-state-repo. So the steps should be:
#
# Pre-upgrade:
#   - Set "prune: false" in argo-application.yaml.
#   - Update the APP_RESYNC_SECONDS environment variable in k8s-configs/base/cluster-tools/kustomization.yaml to
#     increase the sync interval of the CD tool, e.g. 3600 for 1 hour.
#   - Wait for the CD replicas to be rolled out.
#
# Upgrade:
#   - Upgrade the cluster-state-repo to the new Beluga version using the upgrade-cluster-state-wrapper.sh script.
#     Refer to the upgrade doc for the Beluga release for more details.
#   - Set "prune: false" in argo-application.yaml.
#   - Update the APP_RESYNC_SECONDS environment variable in k8s-configs/base/cluster-tools/kustomization.yaml to
#     increase the sync interval of the CD tool, e.g. 3600 for 1 hour.
#   - Make changes to this file to roll out the app updates in the right order.
#   - Perform a manual sync from the CD UI to apply the changes.
#   - Continue making changes to this file until all apps are updated.
#
# Post-upgrade:
#  - Set "prune: true" in argo-application.yaml.
#  - Reset the APP_RESYNC_SECONDS to the original default of "60" seconds.
#  - To make them immediately effective, issue a sync to the CD tool.

kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:

# PingDirectory resources
- ../pingdirectory/server

# PingAccess WAS admin and engine resources
- ../pingaccess-was/admin
- ../pingaccess-was/engine

# PingAccess admin and engine resources
- ../pingaccess/admin
- ../pingaccess/engine

# PingFederate admin and engine resources
- ../pingfederate/admin
- ../pingfederate/engine

# Delegated admin resources
- ../pingdelegator/server

# Ping Data Sync resources
- ../pingdatasync/server

# WARNING!!!
#
# Exposing the pingdataconsole in production is not recommended. The console resources only exist for debugging
# Delegated Admin configuration. Do NOT make any configuration changes via the data console. That can cause errors
# while applying future updates through the cluster-state repo.
#
# To deploy the console, uncomment the following line. Once debugging is complete, comment it out once again. To login
# into the admin console, use "pingdirectory:1636" for the Server field and "administrator/<default-password>"
# for the Username/Password fields.

#- ../pingdataconsole
