kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud

resources:
- ../../../base
- ../../../base/aws
<<<<<<< HEAD
- ../../../base/pingdirectory/aws
- ../../../base/pingfederate/aws
- ../../../base/pingaccess/aws

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingdirectory-environment-variables
  behavior: merge
  envs:
  - pingdirectory/env_vars

patchesStrategicMerge:
- pingdirectory/wait-for-service.yaml
- pingdirectory/limits.yaml

- pingfederate/engine-init-env.yaml
- pingfederate/hpa-limits.yaml
- pingfederate/engine-limits.yaml

- pingaccess/engine-init-env.yaml
- pingaccess/engine-limits.yaml
- pingaccess/hpa-limits.yaml

- pingaccess-was/engine-init-env.yaml
- pingaccess-was/engine-limits.yaml
=======
>>>>>>> [skip pipeline] PDO-1576 add more granular control on all PingCloud base products
