kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- cluster-autoscaler.yaml

# Point to the ping-cluster-tools repo equivalents pushed to ECR
images:
- name: registry.k8s.io/autoscaling/cluster-autoscaler
  newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/autoscaling/cluster-autoscaler
  newTag: v1.34.2
                   
patches:
  - target:
      # Specify the resource you want to modify
      kind: Deployment
      name: cluster-autoscaler
    patch: | 

      # Add annotation to the Deployment

      - op: add
        path: /metadata/annotations
        value:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

      # Add multiple commands using YAML-style array

      - op: remove
        path: /spec/template/spec/containers/0/command/3
        value: --cloud-provider=aws

      - op: replace
       # keeping v==1 since that will lower our logs going to cloudwatch
        path: /spec/template/spec/containers/0/command/1
        value: --v=1

      - op: add
        path: /spec/template/spec/containers/0/command/-
        value:
          "--balancing-ignore-label=eks.amazonaws.com/sourceLaunchTemplateId"

      - op: add
        path: /spec/template/spec/containers/0/command/-
        value:
          "--balancing-ignore-label=eks.amazonaws.com/sourceLaunchTemplateVersion"

      - op: add
        path: /spec/template/spec/containers/0/command/-
        value:
          "--balancing-ignore-label=failure-domain.beta.kubernetes.io/zone"

      - op: add
        path: /spec/template/spec/containers/0/command/-
        value:
          "--balancing-ignore-label=topology.ebs.csi.aws.com/zone"

      - op: add
        path: /spec/template/spec/containers/0/command/-
        value:
          "--balancing-ignore-label=topology.kubernetes.io/zone"

      # New label automatically added to node groups as of EKS 1.30 - ignore it in order to make sure each node group is 
      # treated similarly for scale-up, in combination with "--balance-similar-node-groups=true"
      - op: add
        path: /spec/template/spec/containers/0/command/-
        value:
          "--balancing-ignore-label=topology.k8s.aws/zone-id"

      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent

      - op: add
        path: /spec/template/spec/containers/0/command/-
        value:
          "--balance-similar-node-groups=true"
      - op: add
        path: /spec/template/spec/containers/0/securityContext/privileged
        value: false
      - op: add
        path: /spec/template/spec/containers/0/securityContext/runAsNonRoot
        value: true