kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- namespace.yaml
- ../base
- rbac.yaml
- hpa.yaml
- ingress-class.yaml

namespace: ingress-nginx-private

labels:
  # Replace all labels as our OOTB nginx base includes labels like app.kubernetes.io/instance which is also used by ArgoCD
  - pairs:
      app.kubernetes.io/role: ingress-nginx-private
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
    includeTemplates: true
    includeSelectors: true
  # Do NOT add these labels to selectors - selectors changes on Deployments are immutable and lead to upgrade challenges
  # and downtime
  # NOTE: must be updated with each upgrade until we are using Helm
  - pairs:
      app.kubernetes.io/version: 1.11.2
      app: ingress-nginx
    includeTemplates: true
    includeSelectors: false

patchesJson6902:
- path: add-deployment-args.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-ingress-controller
- path: make-service-private.yaml
  target:
    version: v1
    kind: Service
    name: ingress-nginx

# Add annotation to IngressClass
patches:
- target:
    kind: IngressClass
    name: nginx-private
  patch: |-
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1enable-annotation-validation
      value: "true"

### SELECTOR UPDATE ###
# Because the selector path is deleted in base, we do a strategic merge patch to add all labels
#
# IMPORTANTLY, we add the 'app: ingress-nginx' label which is new with P1AS 1.19.1
# This new label allows us to upgrade future deployments without having to recreate the deployment resource itself,
# while also migrating off of the existing deployment which has the same selector labels.
# When upgrading the new Deployment can be created after the old one is orphaned and the new Deployment will select the
# new pods but not the old, orphaned ones, which can lead to unexpected behavior.
# See: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#selector
#
# Meanwhile, the Service selects any previous or new pods allowing for zero downtime upgrades
#######################
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-ingress-controller
    spec:
      selector:
        matchLabels:
          app: ingress-nginx
          app.kubernetes.io/component: controller
          app.kubernetes.io/name: ingress-nginx
          app.kubernetes.io/part-of: ingress-nginx
          app.kubernetes.io/role: ingress-nginx-private

# Strategic merge patches for the 'nginx-configuration' ConfigMap
- path: add-custom-log-format.yaml
- path: add-custom-logic-to-filter-pf-pa-heartbeat-endpoint.yaml