# This defines the external ingress for the pingdelegator service

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingdelegator-ext-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    selfservice.metadata.pingidentity.com/name: "Delegated Admin Console"
    selfservice.metadata.pingidentity.com/category: "Product Administration"
    selfservice.metadata.pingidentity.com/displayURL: "https://ext-pingdelegator.ping-demo.com/delegator"
  labels:
    selfservice: urls
spec:
  ingressClassName: nginx-public
  tls:
  - hosts:
    - ext-pingdelegator.ping-demo.com
  rules:
  - host: ext-pingdelegator.ping-demo.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: pingdelegator
            port:
              number: 1443