kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ${PING_CLOUD_NAMESPACE}

resources:
  - ../base/custom-resources
  - custom-resources

helmCharts:
  - name: p1as-self-service
    additionalValuesFiles:
      - ../../values-files/base/values.yaml   # base values.yaml
      - ../../values-files/${REGION_NICK_NAME}/values.yaml   # regional values.yaml
      - values.yaml   # app specific values.yaml
    version: v99.0.0-RC1
    repo: oci://${ECR_REGISTRY_NAME}/p1as-self-service

### This field is used to trigger a resync of the p1as-self-service helm chart ###
configMapGenerator:
  - name: self-service-last-update-reason
    literals:
      - UPDATE_REASON=""
  ### This is needed for the empty custom-patches.yaml file to work ###
  - name: self-service-custom-placeholder
  ### This is needed for the empty custom-patches.yaml file to work in base folder ###
  - name: self-service-custom-placeholder-base      

patchesStrategicMerge:
  ### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###
  - custom-patches.yaml
  - ../base/custom-patches.yaml
