apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  annotations:
    self-service.metadata.pingidentity.com/name: "Argo CD Console"
    self-service.metadata.pingidentity.com/description: "Native Argo CD console for cluster orchestration administration"
    self-service.metadata.pingidentity.com/category: "Platform Administration"
    self-service.metadata.pingidentity.com/displayURL: "https://argocd.ping-demo.com/"
  labels:
    self-service.urls/managed: "true"
spec:
  ingressClassName: nginx-public
  rules:
  - host: argocd.ping-demo.com
    http:
      paths:
      - backend:
          service:
            name: pingaccess-was
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - argocd.ping-demo.com
