apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  annotations:
    selfservice.metadata.pingidentity.com/name: "Prometheus Console"
    selfservice.metadata.pingidentity.com/description: "Native Prometheus expression browser for querying raw metrics"
    selfservice.metadata.pingidentity.com/category: "Platform Administration"
    selfservice.metadata.pingidentity.com/displayURL: "https://prometheus.ping-demo.com/"
  labels:
    selfservice: urls
spec:
  ingressClassName: nginx-public
  rules:
  - host: prometheus.ping-demo.com
    http:
      paths:
      - backend:
          service:
            name: pingaccess-was
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - prometheus.ping-demo.com
