apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  annotations:
    selfservice.metadata.pingidentity.com/name: "Grafana Console"
    selfservice.metadata.pingidentity.com/description: "Native Grafana console for querying and visualizing metrics"
    selfservice.metadata.pingidentity.com/category: "Platform Administration"
    selfservice.metadata.pingidentity.com/displayURL: "https://monitoring.ping-demo.com/"
  labels:
    selfservice: urls
spec:
  ingressClassName: nginx-public
  rules:
  - host: monitoring.ping-demo.com
    http:
      paths:
      - backend:
          service:
            name: pingaccess-was
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - monitoring.ping-demo.com
