apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingfederate-admin-console-ingress
  annotations:
    self-service.metadata.pingidentity.com/name: "PingFederate Admin Console"
    self-service.metadata.pingidentity.com/category: "Product Administration"
    self-service.metadata.pingidentity.com/displayURL: "https://pingfederate-admin.ping-demo.com/pingfederate/app"
  labels:
    self-service.urls/managed: "true"
spec:
  ingressClassName: nginx-public
  rules:
  - host: pingfederate-admin.ping-demo.com
    http:
      paths:
      - backend:
          service:
            name: pingaccess-was
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - pingfederate-admin.ping-demo.com
