apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logs-ingress
  annotations:
    self-service.metadata.pingidentity.com/name: "OpenSearch Dashboards"
    self-service.metadata.pingidentity.com/description: "Native OpenSearch console for visualizing and analyzing logs"
    self-service.metadata.pingidentity.com/category: "Platform Administration"
    self-service.metadata.pingidentity.com/displayURL: "https://logs.ping-demo.com/"
  labels:
    self-service.urls/managed: "true"
spec:
  ingressClassName: nginx-public
  rules:
  - host: logs.ping-demo.com
    http:
      paths:
      - backend:
          service:
            name: pingaccess-was
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - logs.ping-demo.com
