apiVersion: v1
kind: ConfigMap
metadata:
  name: pingaccess-init
data:
  init.sh: |-
    #!/bin/sh -x

    #--- Wait for services if there are any dependent services we must wait on --- #
    if test ! -z "${WAIT_FOR_SERVICES}"; then
      for SERVICE in "${WAIT_FOR_SERVICES}"; do
        until nslookup "${SERVICE}"; do
          echo "Waiting for service ${SERVICE}"
          sleep 2
        done
      done
    fi

    #--- Sleep for the configured initial delay seconds --- #
    SLEEP_SECONDS=${INITIAL_DELAY_SECONDS:-0}
    sleep ${SLEEP_SECONDS}

    #--- Copy SSH configuration files --- #
    test -f /known_hosts && cp /known_hosts /.ssh
    test -f /id_rsa && cp /id_rsa /.ssh

    # Install kubectl
    echo "Installing kubectl"
    curl https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl -o /data/kubectl
    chmod +x /data/kubectl

    exit 0

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pingaccess-pre-stop
data:
  pre-stop.sh: |-
    #!/bin/sh -x

    echo "Starting pre-stop hook"

    SHORT_HOST_NAME=$(hostname)
    ORDINAL=$(echo ${SHORT_HOST_NAME##*-})
    echo "Pod ordinal: ${ORDINAL}"

    NUM_REPLICAS=$(kubectl get statefulset "${K8S_STATEFUL_SET_NAME_PINGACCESS}" -o jsonpath='{.spec.replicas}')
    echo "Number of replicas: ${NUM_REPLICAS}"

    if test ${ORDINAL} -lt ${NUM_REPLICAS}; then
      echo "Not removing server since it is still in the topology"
      exit 0
    fi

    # Retrieve Engine ID
    ENGINE_ID=$( curl -k --retry ${API_RETRY_LIMIT} \
                         --max-time ${API_TIMEOUT_WAIT} \
                         --retry-delay 1 \
                         --retry-connrefused \
                         -u ${PA_ADMIN_USER_USERNAME}:${PA_ADMIN_USER_PASSWORD} \
                         -H "X-Xsrf-Header: PingAccess " \
                         -X GET https://${K8S_SERVICE_NAME_PINGACCESS_ADMIN}:9000/pa-admin-api/v3/engines | \
                         jq --arg SHORT_HOST_NAME "${SHORT_HOST_NAME}" \
                         '.items[] | select(.name==$SHORT_HOST_NAME) | .id' )

    # Delete Engine
    curl -k --retry ${API_RETRY_LIMIT} \
                         --max-time ${API_TIMEOUT_WAIT} \
                         --retry-delay 1 \
                         --retry-connrefused \
                         -u ${PA_ADMIN_USER_USERNAME}:${PA_ADMIN_USER_PASSWORD} \
                         -H "X-Xsrf-Header: PingAccess " \
                         -X DELETE https://${K8S_SERVICE_NAME_PINGACCESS_ADMIN}:9000/pa-admin-api/v3/engines/${ENGINE_ID} \
                         > /dev/null