kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud

resources:
- ../../../../base/pingaccess-was/admin/aws

patchesStrategicMerge:
- admin-limits.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: pingaccess-was-admin
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/6/resources/limits/cpu
        value: 2
      - op: replace
        path: /spec/template/spec/initContainers/6/resources/limits/memory
        value: 6Gi
      - op: replace
        path: /spec/template/spec/initContainers/6/resources/requests/cpu
        value: 2
      - op: replace
        path: /spec/template/spec/initContainers/6/resources/requests/memory
        value: 6Gi
