kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
- elasticsearch-ilm-policies.yaml
- elasticsearch-index-bootstraps.yaml
- elasticsearch-index-templates.yaml
- enrichment-cache.yaml
- https://github.com/pingidentity/ping-cloud-dashboards/kibana?ref=v1.17-dev-branch
- logstash-search-templates.yaml
- kibana-alerts.yaml