kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/${KUSTOMIZE_BASE}/logging?ref=${K8S_GIT_BRANCH}
- ${DASH_REPO_URL}/os-dashboards?ref=${DASH_REPO_BRANCH}

images:
- name: ${ECR_REGISTRY_NAME}/pingcloud-monitoring/logstash${ECR_ENV}
  newName: ${ECR_REGISTRY_NAME}/pingcloud-monitoring/logstash${ECR_ENV}
  newTag: ${LOGSTASH_IMAGE_TAG}
- name: ${ECR_REGISTRY_NAME}/pingcloud-monitoring/os-bootstrap${ECR_ENV}
  newName: ${ECR_REGISTRY_NAME}/pingcloud-monitoring/os-bootstrap${ECR_ENV}
  newTag: ${OS_BOOTSTRAP_IMAGE_TAG}


generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: elk-environment-variables
  behavior: merge
  envs:
  - env_vars

- name: logging-bootstrap-environment-variables
  behavior: merge
  literals:
    - SERVICE_SSM_PATH_PREFIX=${SERVICE_SSM_PATH_PREFIX}
    - REGION=${REGION}

- name: os-notifications-channels
  behavior: merge
  files:
    - notifications/sns.json

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: cluster-info
    namespace: elastic-stack-logging
  data:
    cluster.name: ${CLUSTER_NAME}
    logs.region: ${REGION}
    tenant_domain: ${TENANT_DOMAIN}
    primary_tenant_domain: ${PRIMARY_TENANT_DOMAIN}

### enrichment-bootstrap service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: enrichment
    name: enrichment
    annotations:
      purpose: service-account-for-ping-cloud-stack
      ${IRSA_PING_ANNOTATION_KEY_VALUE}

- |-
  # Add IRSA role annotation to logstash-elastic service account
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: logstash-elastic
    namespace: elastic-stack-logging
    annotations:
      purpose: service-account-for-logstash-elastic
      ${IRSA_LOGSTASH_ANNOTATION_KEY_VALUE}

- |-
  # Add IRSA role annotation to opensearch service account
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: opensearch
    namespace: elastic-stack-logging
    annotations:
      purpose: service-account-for-opensearch
      ${IRSA_OPENSEARCH_ANNOTATION_KEY_VALUE}


patchesJson6902:
- target:
    kind: Service
    name: opensearch-ingest
    namespace: elastic-stack-logging
    version: v1
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: opensearch.${DNS_ZONE}

- target:
    group: ""
    version: v1
    kind: ConfigMap
    name: fluent-bit-config
  patch: |-
    - op: replace
      path: /data/newrelic_cluster_name
      value: "${NEW_RELIC_ENVIRONMENT_NAME}"
