kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- namespace.yaml
- ../base
- rbac.yaml
- hpa.yaml

namespace: ingress-nginx-private

commonLabels:
  app.kubernetes.io/role: ingress-nginx-private

patchesJson6902:
- path: add-deployment-args.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-ingress-controller

- path: make-service-private.yaml
  target:
    version: v1
    kind: Service
    name: ingress-nginx