kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud

resources:
- ../../base
- ../../base/pingdirectory/aws
- ../../base/pingfederate/aws
- ../../base/pingaccess/aws
- ../../base/aws

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:

- name: pingdirectory-environment-variables
  behavior: merge
  envs:
  - pingdirectory/env_vars

patchesStrategicMerge:
- pingdirectory/limits.yaml
- pingfederate/admin-init-env.yaml
- pingfederate/engine-init-env.yaml
- pingfederate/admin-limits.yaml
- pingfederate/engine-limits.yaml	
- pingfederate/hpa-limits.yaml
- pingaccess/admin-init-env.yaml
- pingaccess/engine-init-env.yaml
- pingaccess/admin-limits.yaml	
- pingaccess/engine-limits.yaml	
- pingaccess/hpa-limits.yaml
