kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
# Apply PingAccess-WAS runtime engine deployment resources
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingaccess-was/engine?ref=${K8S_GIT_BRANCH}

images:
- name: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingaccess-was${ECR_ENV}
  newName: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingaccess-was${ECR_ENV}
  newTag: ${PINGACCESS_WAS_IMAGE_TAG}

patchesStrategicMerge:
  - remove-unneeded-ingresses.yaml

patchesJson6902:

### PingAccess WAS Engine Last Update Config Map ###
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: pingaccess-was
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: pingaccess-was-last-update-config

### Separated Ingresses through PA-WAS engines ###

# Argo CD
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: argocd-ingress
  patch: |-
    - op: replace
      path: /metadata/annotations/selfservice.metadata.pingidentity.com~1displayURL
      value: "https://argocd.${DNS_ZONE}/"
    - op: replace
      path: /spec/tls/0/hosts/0
      value: argocd.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: argocd.${DNS_ZONE}

# Healthcheck
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: healthcheck-httpbin-pa-was-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: healthcheck-httpbin-pa-was.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: healthcheck-httpbin-pa-was.${DNS_ZONE}

# Monitoring
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: monitoring-ingress
  patch: |-
    - op: replace
      path: /metadata/annotations/selfservice.metadata.pingidentity.com~1displayURL
      value: "https://monitoring.${DNS_ZONE}/"
    - op: replace
      path: /spec/tls/0/hosts/0
      value: monitoring.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: monitoring.${DNS_ZONE}

# PingCentral Admin
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingcentral-admin-ingress
  patch: |-
    - op: replace
      path: /metadata/annotations/selfservice.metadata.pingidentity.com~1displayURL
      value: "https://pingcentral-admin.${DNS_ZONE}/"
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingcentral-admin.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: pingcentral-admin.${DNS_ZONE}

# Prometheus
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: prometheus-ingress
  patch: |-
    - op: replace
      path: /metadata/annotations/selfservice.metadata.pingidentity.com~1displayURL
      value: "https://prometheus.${DNS_ZONE}/"
    - op: replace
      path: /spec/tls/0/hosts/0
      value: prometheus.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: prometheus.${DNS_ZONE}
