kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/base/pingfederate/ff-external-ingress?ref=${K8S_GIT_BRANCH}

patchesJson6902:

# pingcloud-metadata ingress
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingfederate-admin-ext-ingress
  patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: ext-pingfederate-admin-api.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: ext-pingfederate-admin-api.${DNS_ZONE}
