kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

configMapGenerator:
- name: logstash-pipeline-main
  files:
    - 01-input.conf
    - 02-input-filters.conf
    - 03-ingress-filters.conf
    - 04-ping-apps-filters.conf
    - 05-siem-sort-filters.conf
    - 06-siem-detailed-filters.conf
    - 07-pre-outputs-filter.conf
    - 08-outputs.conf