kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:

# PingCloud common resources and configs. These should always be included. DO NOT comment them out.
- pingcommon
- pingdirectory/config
- pingaccess-was/config
- pingaccess-was/ff-external-ingress
- pingaccess/config
- pingfederate/config
- pingdelegator/config
- pingdatasync/config
# Provisioning is not enabled by default, but the kustomize file is managed directly by generate-cluster/update-cluster
- pingfederate/provisioning

# The following resource reference includes all ping applications by default. However, it may be tweaked to roll out
# applications independent of one another to enforce proper dependency order. Refer to the docs in kustomization.yaml
# under the granular-updates directory.
- granular-updates

configMapGenerator:

### PD topology descriptor.json file. ###
### Refer to profiles/pingdirectory/topology/descriptor-profiles.json.sample for more details. ###
- name: topology-descriptor
  behavior: merge
  files:
  - descriptor.json

patchesStrategicMerge:

### Ping app known_hosts file ###

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: known-hosts-config
  data:
    known_hosts: |
      ${KNOWN_HOSTS_CLUSTER_STATE_REPO}

### Ping cloud stack service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ping-serviceaccount
    annotations:
      purpose: service-account-for-ping-cloud-stack
      ${IRSA_PING_ANNOTATION_KEY_VALUE}

### Ping directory backup restore  service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: pingdirectory-ops-serviceaccount
    annotations:
      purpose: service-account-for-ping-directory-ops
      ${IRSA_PING_ANNOTATION_KEY_VALUE}

### Ping access service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: pingaccess-serviceaccount
    annotations:
      purpose: service-account-for-ping-access
      ${IRSA_PA_ANNOTATION_KEY_VALUE}

### Ping directory service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: pingdirectory-serviceaccount
    annotations:
      purpose: service-account-for-ping-directory
      ${IRSA_PD_ANNOTATION_KEY_VALUE}

### Ping federate service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: pingfederate-serviceaccount
    annotations:
      purpose: service-account-for-ping-federate
      ${IRSA_PF_ANNOTATION_KEY_VALUE}

### NOTE: For now, use the irsa-ping role as its the only one which exists
### Ping federate admin service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: pingfederate-admin-serviceaccount
    annotations:
      ${IRSA_PING_ANNOTATION_KEY_VALUE}

### P14C Bootstrap service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: p14c-bootstrap-serviceaccount
    annotations:
      purpose: service-account-for-ping-cloud-stack
      ${IRSA_PING_ANNOTATION_KEY_VALUE}

#patchesJson6902:

# pingcloud-metadata ingress
#- target:
#    group: networking.k8s.io
#    version: v1
#    kind: Ingress
#    name: metadata-ingress
#  patch: |
#    - op: replace
#      path: /spec/tls/0/hosts/0
#      value: metadata.${DNS_ZONE}
#    - op: replace
#      path: /spec/rules/0/host
#      value: metadata.${DNS_ZONE}

# pingcloud-healthcheck ingress
#- target:
#    group: networking.k8s.io
#    version: v1
#    kind: Ingress
#    name: healthcheck-ingress
#  patch: |
#    - op: replace
#      path: /spec/tls/0/hosts/0
#      value: healthcheck.${DNS_ZONE}
#    - op: replace
#      path: /spec/rules/0/host
#      value: healthcheck.${DNS_ZONE}
