kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- cert-manager
- cluster-autoscaler
- service-discovery
- health
- logging
- metrics
- monitoring
- security
- pod-reaper
- kube-downscaler
