kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- cert-manager
- cluster-autoscaler
- service-discovery
- health
- ingress
- logging
- metrics
- monitoring
- security
- ebs-driver
- efs-driver
- pod-reaper
- notification
- kube-downscaler
