kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
- namespace.yaml
- ingress.yaml
- elasticsearch.yaml
#- fluentd.yaml
- kibana.yaml
- logstash.yaml
- enrichment-cache.yaml
- enrichment-job.yaml
