kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - namespace.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - daemonset.yaml
  - deployment.yaml
  - job.yaml
  - mutationwebhookconfiguration.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml
  - secret.yaml
  - role.yaml
  - rolebinding.yaml

# Removing out the helm hook annotation as it is causing argo to sync these resources before karpenter
patches:
  - target:
      kind: ClusterRole
      name: nri-bundle-nri-metadata-injection-admission
    patch: |
      - op: remove
        path: /metadata/annotations/helm.sh~1hook
      - op: remove
        path: /metadata/annotations/helm.sh~1hook-delete-policy

  - target:
      kind: ClusterRoleBinding
      name: nri-bundle-nri-metadata-injection-admission
    patch: |
      - op: remove
        path: /metadata/annotations/helm.sh~1hook
      - op: remove
        path: /metadata/annotations/helm.sh~1hook-delete-policy

  - target:
      kind: Role
      name: nri-bundle-nri-metadata-injection-admission
    patch: |
      - op: remove
        path: /metadata/annotations/helm.sh~1hook
      - op: remove
        path: /metadata/annotations/helm.sh~1hook-delete-policy

  - target:
      kind: RoleBinding
      name: nri-bundle-nri-metadata-injection-admission
    patch: |
      - op: remove
        path: /metadata/annotations/helm.sh~1hook
      - op: remove
        path: /metadata/annotations/helm.sh~1hook-delete-policy

  - target:
      kind: Job
      name: nri-bundle-nri-metadata-injection-admission-create
    patch: |
      - op: remove
        path: /metadata/annotations/helm.sh~1hook
      - op: remove
        path: /metadata/annotations/helm.sh~1hook-delete-policy

  - target:
      kind: Job
      name: nri-bundle-nri-metadata-injection-admission-patch
    patch: |
      - op: remove
        path: /metadata/annotations/helm.sh~1hook
      - op: remove
        path: /metadata/annotations/helm.sh~1hook-delete-policy

  - target:
      kind: ServiceAccount
      name: nri-bundle-nri-metadata-injection-admission-patch
    patch: |
      - op: remove
        path: /metadata/annotations/helm.sh~1hook
      - op: remove
        path: /metadata/annotations/helm.sh~1hook-delete-policy

  - target:
      kind: ServiceAccount
      name: nri-bundle-nri-metadata-injection-admission
    patch: |
      - op: remove
        path: /metadata/annotations/helm.sh~1hook
      - op: remove
        path: /metadata/annotations/helm.sh~1hook-delete-policy
