kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- git-ops
- cert-manager
- cluster-autoscaler
- service-discovery
- logging
- metrics
- monitoring
- security
- pod-reaper
- health
#- karpenter
- kube-downscaler
