kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- git-ops
- cert-manager
- cluster-autoscaler
- ebs-driver
- efs-driver
- service-discovery
- ingress
- logging
- metrics
- monitoring
- security
- pod-reaper
- health
- pgo
- notification
- karpenter
- kube-downscaler
