kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/${KUSTOMIZE_BASE}/karpenter/${ACCOUNT_TYPE}?ref=${K8S_GIT_BRANCH}

patchesStrategicMerge:

# Patch karpenter configuration by incorporating specific details related to CDE

- |-
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: karpenter
   namespace: kube-system
 spec:
   template:
     spec:
       containers:
         - name: controller
           env:
            - name: CLUSTER_NAME
              value: "${CLUSTER_NAME}"
            - name: CLUSTER_ENDPOINT
              value: "${CLUSTER_ENDPOINT}"
            - name: DISABLE_WEBHOOK
              value: "false"
            - name: INTERRUPTION_QUEUE
              value: "interruption-${CLUSTER_NAME}"
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: karpenter
    namespace: kube-system
    annotations:
      purpose: karpenter-nodepool
      ${KARPENTER_ROLE_ANNOTATION_KEY_VALUE}

- |-
  apiVersion: karpenter.k8s.aws/v1beta1
  kind: EC2NodeClass
  metadata:
    name: default
  spec:
    securityGroupSelectorTerms:
      - tags:
          karpenter.sh/discovery: "${CLUSTER_NAME}"
    subnetSelectorTerms:
      - tags:
          karpenter.sh/discovery: "${CLUSTER_NAME}"
    instanceProfile: "${KARPENTER_INSTANCE_PROFILE}"

- |-
  apiVersion: karpenter.k8s.aws/v1beta1
  kind: EC2NodeClass
  metadata:
    name: pd-only
  spec:
    securityGroupSelectorTerms:
      - tags:
          karpenter.sh/discovery: "${CLUSTER_NAME}"
    subnetSelectorTerms:
      - tags:
          karpenter.sh/discovery: "${CLUSTER_NAME}"
    instanceProfile: "${KARPENTER_INSTANCE_PROFILE}"
