kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/${KUSTOMIZE_BASE}/karpenter/${ACCOUNT_TYPE}?ref=${K8S_GIT_BRANCH}

patchesStrategicMerge:

# Patch karpenter configuration by incorporating specific details related to CDE
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: karpenter-global-settings
    namespace: karpenter
  data:
    "aws.clusterEndpoint": "${CLUSTER_ENDPOINT}"
    "aws.clusterName": "${CLUSTER_NAME}"

- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: karpenter
    namespace: karpenter
    annotations:
      purpose: karpenter-provisioner
      ${KARPENTER_ROLE_ANNOTATION_KEY_VALUE}

- |-
  apiVersion: karpenter.k8s.aws/v1alpha1
  kind: AWSNodeTemplate
  metadata:
    name: default
  spec:
    securityGroupSelector:
      karpenter.sh/discovery: "${CLUSTER_NAME}"
    subnetSelector:
      karpenter.sh/discovery: "${CLUSTER_NAME}"

- |-
  apiVersion: karpenter.k8s.aws/v1alpha1
  kind: AWSNodeTemplate
  metadata:
    name: pd-only
  spec:
    securityGroupSelector:
      karpenter.sh/discovery: "${CLUSTER_NAME}"
    subnetSelector:
      karpenter.sh/discovery: "${CLUSTER_NAME}"

- |-
  apiVersion: karpenter.k8s.aws/v1alpha1
  kind: AWSNodeTemplate
  metadata:
    name: pgo-only
  spec:
    securityGroupSelector:
      karpenter.sh/discovery: "${CLUSTER_NAME}"
    subnetSelector:
      karpenter.sh/discovery: "${CLUSTER_NAME}"

# Setting Karpenter replicas as at this stage of deployment all the CDE specific configuration should be available for Karpenter to utilize.
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: karpenter
    namespace: karpenter
  spec:
    replicas: 2

# Initially, by default we will disable Karpenter from taking over node deployment. As customers migrate, we will gradually enable this feature.
# Once all of our customers have finished migrating, we will enable Karpenter by default.
# To enable Karpenter, you need to comment out the line below.
- disable-karpenter.yaml
