kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:

# PingCloud common resources and configs. These should always be included. DO NOT comment them out.
- pingcommon
- pingcentral
- pingaccess-was/config
- pingaccess-was/admin
- pingaccess-was/engine
- pingaccess-was/ff-external-ingress

patchesStrategicMerge:

### The removal of these patches is handled automatically via git-ops-command.sh script, manual toggling is not needed ###
- pingaccess-was/ff-external-ingress/remove-external-ingress.yaml

### Ping app known_hosts file ###

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: known-hosts-config
  data:
    known_hosts: |
      ${KNOWN_HOSTS_CLUSTER_STATE_REPO}

### Ping cloud stack service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ping-serviceaccount
    annotations:
      purpose: service-account-for-ping-cloud-stack
      ${IRSA_PING_ANNOTATION_KEY_VALUE}

### P14C Bootstrap service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: p14c-bootstrap-serviceaccount
    annotations:
      purpose: service-account-for-ping-cloud-stack
      ${IRSA_PING_ANNOTATION_KEY_VALUE}
