kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:

# PingCloud common resources and configs. These should always be included. DO NOT comment them out.
- pingcommon
- pingcentral

configMapGenerator:

### PD topology descriptor.json file. ###
### Refer to profiles/pingdirectory/topology/descriptor-profiles.json.sample for more details. ###
- name: topology-descriptor
  behavior: merge
  files:
  - descriptor.json

patchesStrategicMerge:

### Ping app known_hosts file ###

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: known-hosts-config
  data:
    known_hosts: |
      ${KNOWN_HOSTS_CLUSTER_STATE_REPO}

### Ping cloud stack service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ping-serviceaccount
    annotations:
      purpose: service-account-for-ping-cloud-stack
      ${IRSA_PING_ANNOTATION_KEY_VALUE}

patchesJson6902:

# pingcloud-metadata ingress
- target:
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
    name: metadata-ingress
  patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: metadata.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: metadata.${DNS_ZONE}
