# This defines the pingfederate deployment.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingfederate
spec:
  replicas: 1
  template:
    metadata:
      name: pingfederate
      annotations:
        lastUpdateTime: "NA"
    spec:
      containers:
      - name: pingfederate
        image: pingidentity/pingfederate:9.3.1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
        readinessProbe:
          exec:
            command: [ liveness.sh ]
          periodSeconds: 30
          failureThreshold: 10
        livenessProbe:
          exec:
            command: [ liveness.sh ]
          periodSeconds: 30
          failureThreshold: 10
        ports:
        - containerPort: 9999
          name: pf-admin
        - containerPort: 9031
          name: pf-runtime
        envFrom:
        - configMapRef:
            name: pingfederate-environment-variables
        - secretRef:
            name: devops-secret