# This defines the pingfederate deployment.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingfederate
spec:
  replicas: 1
  template:
    metadata:
      name: pingfederate
      annotations:
        lastUpdateTime: "NA"
    spec:
      containers:
      - name: pingfederate
        image: pingidentity/pingfederate:9.3.0-edge
        ports:
        - containerPort: 9999
          name: pf-admin
        - containerPort: 9031
          name: pf-runtime
        envFrom:
          - configMapRef:
              name: pingfederate-environment-variables