kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  role: pingfederate

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingfederate-environment-variables
  env: env_vars