kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: prometheus

resources:
- namespace.yaml
- grafana.yaml
- prometheus.yaml
- alertmanager.yaml
- prometheus-alerts.yaml
- grafana-dashboards.yaml
- prometheus-job-exporter.yaml
- dashboards

configMapGenerator:
- name: prometheus-environment-variables
  envs:
    - env_vars