apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  name: prometheus-agent
spec:
  replicas: 2
  containers:
    - name: prometheus
      envFrom:
        - configMapRef:
            name: prometheus-environment-variables
  scrapeInterval: 30s
  scrapeTimeout: 5s
  externalLabels:
    k8s_cluster_name: ${CLUSTER_NAME}-${TENANT_NAME}-${REGION_NICK_NAME}
    replica_cluster_name: ${CLUSTER_NAME}-${TENANT_NAME}-${REGION_NICK_NAME}
  scrapeConfigSelector:
    matchLabels:
      prometheus: system-monitoring-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      prometheus: agent
  podMonitorSelector:
    matchLabels:
      prometheus: agent
  remoteWrite:
    - url: 'http://thanos-receive-headless:19291/api/v1/receive'
  enableFeatures:
    - agent
    - expand-external-labels
  securityContext:
    fsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
  serviceAccountName: prometheus
  image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/prom/prometheus:v2.47.0
  resources:
    limits:
      cpu: 500m
      memory: 4000Mi
    requests:
      cpu: 100m
      memory: 512Mi