kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
# Apply Ping Delegated Admin deployment resources
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingdelegator/server?ref=${K8S_GIT_BRANCH}

images:
- name: ${JFROG_REGISTRY_NAME}/pingidentity/pingdelegator
  newTag: ${PINGDELEGATOR_IMAGE_TAG}

generatorOptions:
  disableNameSuffixHash: true

patchesJson6902:

### Ping Delegated Admin Last Update Config Map ###
- target:
    group: apps
    version: v1
    kind: Deployment
    name: pingdelegator
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: pingdelegator-last-update-config

# Ping Delegated Admin
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingdelegator-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingdelegator.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: pingdelegator.${DNS_ZONE}
