kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingfederate/engine/cloud-generic/ff-radius-proxy?ref=${K8S_GIT_BRANCH}

# configMapGenerator:
#   - name: pingcloud-radsecproxy-environment-variables
#     behavior: merge
#     envs:
#     - ../../env_vars