# This defines the ingress for the pingaccess-was runtime service

# NOTE: it will only work if an ingress controller (e.g. nginx) is running on
# your cluster.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingaccess-was-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
      SecRuleEngine DetectionOnly
      SecRequestBodyAccess On
      SecAuditEngine RelevantOnly
      SecAuditLogParts ABCDEFGHIJKZ
      SecAuditLogType Serial
      SecAuditLogFormat JSON
      SecAuditLog /dev/stdout
spec:
  ingressClassName: nginx-public
  tls:
    - hosts:
        - pingaccess-admin-dev.ping-demo.com
        - pingfederate-admin-dev.ping-demo.com
        - monitoring-dev.ping-demo.com
        - prometheus-dev.ping-demo.com
        - logs-dev.ping-demo.com
        - pingcentral-admin-dev.ping-demo.com
        - healthcheck-httpbin-pa-was-dev.ping-demo.com
        - argocd-dev.ping-demo.com

  rules:
    - host: pingaccess-admin-dev.ping-demo.com
      http:
        paths:
          # This rule gives external access to the PingAccess admin service
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pingaccess-was
                port:
                  number: 443
    - host: pingfederate-admin-dev.ping-demo.com
      http:
        paths:
          # This rule gives external access to the PingFederate admin service
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pingaccess-was
                port:
                  number: 443
    - host: monitoring-dev.ping-demo.com
      http:
        paths:
          # This rule allows external access to Grafana via the pingaccess-was runtime service
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pingaccess-was
                port:
                  number: 443
    - host: prometheus-dev.ping-demo.com
      http:
        paths:
          # This rule allows external access to Prometheus via the pingaccess-was runtime service
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pingaccess-was
                port:
                  number: 443
    - host: logs-dev.ping-demo.com
      http:
        paths:
          # This rule allows external access to OpenSearch Dashboards via the pingaccess-was runtime service
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pingaccess-was
                port:
                  number: 443
    - host: pingcentral-admin-dev.ping-demo.com
      http:
        paths:
          # This rule allows external access to PingCentral via the pingaccess-was runtime service
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pingaccess-was
                port:
                  number: 443
    - host: healthcheck-httpbin-pa-was-dev.ping-demo.com
      http:
        paths:
          # This rule allows external access to the healthcheck-httpbin-pa-was service via the pingaccess-was runtime service
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pingaccess-was
                port:
                  number: 443
    - host: argocd-dev.ping-demo.com
      http:
        paths:
          # This rule allows external access to Argo CD via the pingaccess-was runtime service
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pingaccess-was
                port:
                  number: 443
