kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- storage.yaml
- logstash.yaml
- logstash_pipelines
- hpa.yaml
- logstash-search-template.yaml
- unused-logstash-pv-cleanup.yaml