kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- base
- nodepool.yaml

# Setting priority to the deployment of karpenter resources over other manifests in the ArgoCD deployment order.
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-5"

# Point to the ping-cluster-tools repo equivalents pushed to ECR
images:
  - name: public.ecr.aws/karpenter/controller
    newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/karpenter/controller
    newTag: 0.37.3

patchesStrategicMerge:
- prometheus-metrics.yaml
- karpenter-deployment.yaml

# NOTE: This patch overwrites the common annotation sync wave above since the CRDs must exist first
# This patch does not appear to work using the new `patches` method so be aware that we will need to refactor at that point
patchesJson6902:
  - target:
      version: v1
      kind: CustomResourceDefinition
      name: nodepools.karpenter.sh
    patch: |-
      - op: replace
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-6"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: nodeclaims.karpenter.sh
    patch: |-
      - op: replace
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-6"

  - target:
      version: v1
      kind: CustomResourceDefinition
      name: ec2nodeclasses.karpenter.k8s.aws
    patch: |-
      - op: replace
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-6"
