# This defines the ingress for the pingaccess-was runtime service

# NOTE: it will only work if an ingress controller (e.g. nginx) is running on
# your cluster.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingaccess-was-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules : "true"
    kubernetes.io/ingress.class: nginx-public
spec:
  tls:
  - hosts:
    - pingaccess-was-dev.ping-demo.com
  rules:
  - host: pingaccess-was-dev.ping-demo.com
    http:
      paths:
      # This rule gives external access to the pingaccess-was runtime service
      - path: /
        backend:
          serviceName: pingaccess-was
          servicePort: 443

---

# This defines the ingress for the pingaccess-was admin service

# NOTE: it will only work if an ingress controller (e.g. nginx) is running on
# your cluster.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingaccess-was-admin-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx-private
    # Possible fix for some 502 failures on admin assets and api requests.
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  tls:
  - hosts:
    - pingaccess-was-admin-dev.ping-demo.com
  rules:
  - host: pingaccess-was-admin-dev.ping-demo.com
    http:
      paths:
      # This rule gives access to the pingaccess-was admin services.
      - path: /
        backend:
          serviceName: pingaccess-was-admin
          servicePort: 9000
