kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../base
- custom-resources
- ../base/cluster-tools/logging/pipelines-config.yaml

generatorOptions:
  disableNameSuffixHash: false

### Patch to remove OpenSearch credentials from prometheus-agent, as OS is not deployed in customer-hub
### As such, it will also not be able to start due to missing secret.  Note that patchesStrategicMerge
### will not work here due to parsing issues on volumeMounts.
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: prometheus-agent
      namespace: prometheus
    patch: |
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/1
      - op: remove
        path: /spec/template/spec/volumes/1

patchesStrategicMerge:

### MANUAL UPDATES SECTION - START

## Healthchecks
# Runbook: https://pingidentity.atlassian.net/wiki/spaces/PDA/pages/427688292/How+to+Enable+and+Disable+Healthchecks+-+1.19.0
# To disable all healthchecks (default):
#   - uncomment the disable-all-healthchecks.yaml patch
#   - comment the other patches
#   - set HEALTHCHECKS_ENABLED=false in base/env_vars
# To enable healthchecks for products in the customer-hub primary region (cluster and pa-was health only):
#   - uncomment chub-healthchecks-primary-region-patch.yaml patch
#   - comment the other patches
#   - set HEALTHCHECKS_ENABLED=true in base/env_vars
#   - re-spin pa-was admin pod when argocd syncs these changes
# To enable healthchecks for products in a customer-hub child region (cluster health only):
#   - uncomment the chub-healthchecks-child-region-patch.yaml patch
#   - comment the other patches
#   - set HEALTHCHECKS_ENABLED=true in base/env_vars

- ../base/cluster-tools/health/disable-all-healthchecks.yaml
#- ../base/cluster-tools/health/chub-healthchecks-primary-region-patch.yaml
#- ../base/cluster-tools/health/chub-healthchecks-child-region-patch.yaml


### MANUAL UPDATES SECTION - END

### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###
- custom-patches.yaml

### Remove observability dashboards for undeployed products
- ../base/cluster-tools/monitoring/remove-chub-dashboards.yaml
- ../base/cluster-tools/logging/remove-chub-dashboards.yaml

### Cost saving measures
- ../base/ping-cloud/pingaccess-was/engine/chub-pingaccess-was-scaledown-patch.yaml

### Remove opensearch from chub
- ../base/cluster-tools/logging/disable-opensearch-base-patch.yaml
#- ../base/cluster-tools/logging/disable-opensearch-primary-region-patch.yaml

### Regional enablement - remove admins, backups, etc. from secondary ###
### The removal of these patches is handled automatically via generate-cluster-state script, manual toggling is not needed ###
- ../base/ping-cloud/pingaccess-was/admin/remove-from-secondary-patch.yaml
- ../base/ping-cloud/pingcentral/server/remove-from-secondary-patch.yaml
- ../base/cluster-tools/monitoring/remove-from-secondary-patch.yaml
- ../base/cluster-tools/logging/remove-from-secondary-patch.yaml


configMapGenerator:

### Regional env vars for ELK
- name: elk-environment-variables
  behavior: merge
  envs:
    - logging/env_vars

- name: prometheus-environment-variables
  behavior: merge
  envs:
    - ../base/env_vars
    - env_vars

- name: p1as-bootstrap
  behavior: merge
  envs:
    - ../base/env_vars
    - env_vars

# PingCentral
# Create the config maps that hold the variable for triggering updates of PingCentral
- name: pingcentral-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingcentral/env_vars

# Merge all env_vars into PingCentral common environment variables configmap
- name: pingcentral-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingcentral/env_vars

# PingAccess WAS
# Create the config maps that hold the variable for triggering updates of PA WAS servers
- name: pingaccess-was-admin-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
    - pingaccess-was/admin/env_vars

- name: pingaccess-was-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
    - pingaccess-was/engine/env_vars

# Merge all env_vars into PingAccess WAS environment variables configmaps
- name: pingaccess-was-admin-environment-variables
  behavior: merge
  envs:
    - ../base/env_vars
    - env_vars
    - pingaccess-was/admin/env_vars

- name: pingaccess-was-environment-variables
  behavior: merge
  envs:
    - ../base/env_vars
    - env_vars
    - pingaccess-was/engine/env_vars

# PingCloud P14C bootstrap
- name: pingcloud-p14c-bootstrap-environment-variables
  behavior: merge
  envs:
    - ../base/env_vars
    - env_vars

# ArgoCD
# Merge global and regional env_vars
- name: argocd-bootstrap
  namespace: argocd
  behavior: merge
  envs:
    - ../base/cluster-tools/git-ops/env_vars
    - git-ops/env_vars

- name: p14c-environment-variables
  namespace: argocd
  behavior: merge
  envs:
    - ../base/env_vars
    - env_vars

# Healthcheck probes
- name: cluster-health-environment-variables
  namespace: health
  behavior: merge
  envs:
    - ../base/cluster-tools/health/env_vars
    - ../base/env_vars
    - env_vars