kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
# Apply pingdatasync deployment resources
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingdatasync/server?ref=${K8S_GIT_BRANCH}

images:
- name: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingdatasync
  newTag: ${PINGDATASYNC_IMAGE_TAG}

generatorOptions:
  disableNameSuffixHash: true

patchesJson6902:

### pingdatasync Last Update Config Map ###
- target:
    group: apps
    version: v1
    kind: Deployment
    name: pingdatasync
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: pingdatasync-last-update-config
    - op: replace
      path: /spec/template/spec/affinity/podAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/labelSelector/matchExpressions/0/values/0
      value: ${DATASYNC_P1AS_SYNC_SERVER}

### Ingress patches ###

# pingdatasync admin
- target:
    version: v1
    kind: Service
    name: pingdatasync-admin
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingdatasync-admin.${DNS_ZONE}

